### ISSUE TITLE
Future Development

### ISSUE THREAD

**Issue by brianteeman** [openregion/tinymce-template-plugin#1]
Are there plans for future development of this plugin or is it just intended to be available with future releases of tinymnce that no longer include this.

**Comment by Gruven** [comment]
@brianteeman there will be no new features, only bugfixes for new versions of tinymce

**Comment by brianteeman** [comment]
OK - thanks for confirming that. We https://github.com/joomla/joomla-cms/ have also forked the plugin. At this time we have made no changes or additions but might do in the future. So if it had been in your plans to do the same I would have switched to use your fork so that more people could benefit.
